prevent when exists release

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -33,6 +33,15 @@ jobs:
     name: Pre-release
     runs-on: ubuntu-latest
     steps:
+      - name: Check for release branch
+        run: |
+          if gh api /repos/${{ github.repository }}/git/ref/heads/release/* >/dev/null 2>&1; then
+            echo "There is an active release branch, you can't create a new release."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
+
       - name: Checkout Git Repo
         uses: actions/checkout@v3
         with:
